//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Descripcion
    {
        public int IdDescripcion { get; set; }
        public string Descripcion1 { get; set; }
        public Nullable<int> IdModelo { get; set; }
    
        public virtual Modelo Modelo { get; set; }
    }
}
