//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PruebaAARCOEntities : DbContext
    {
        public PruebaAARCOEntities()
            : base("name=PruebaAARCOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Descripcion> Descripcion { get; set; }
        public virtual DbSet<Marca> Marca { get; set; }
        public virtual DbSet<Modelo> Modelo { get; set; }
        public virtual DbSet<Submarca> Submarca { get; set; }
    
        public virtual ObjectResult<DescripcionGetByIdModelo_Result> DescripcionGetByIdModelo(Nullable<int> idModelo)
        {
            var idModeloParameter = idModelo.HasValue ?
                new ObjectParameter("IdModelo", idModelo) :
                new ObjectParameter("IdModelo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DescripcionGetByIdModelo_Result>("DescripcionGetByIdModelo", idModeloParameter);
        }
    
        public virtual ObjectResult<MarcaGetAll_Result> MarcaGetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MarcaGetAll_Result>("MarcaGetAll");
        }
    
        public virtual ObjectResult<ModeloGetByIdSubmarca_Result> ModeloGetByIdSubmarca(Nullable<int> idSubmarca)
        {
            var idSubmarcaParameter = idSubmarca.HasValue ?
                new ObjectParameter("IdSubmarca", idSubmarca) :
                new ObjectParameter("IdSubmarca", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ModeloGetByIdSubmarca_Result>("ModeloGetByIdSubmarca", idSubmarcaParameter);
        }
    
        public virtual ObjectResult<SubmarcaGetByIdMarca_Result> SubmarcaGetByIdMarca(Nullable<int> idMarca)
        {
            var idMarcaParameter = idMarca.HasValue ?
                new ObjectParameter("IdMarca", idMarca) :
                new ObjectParameter("IdMarca", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SubmarcaGetByIdMarca_Result>("SubmarcaGetByIdMarca", idMarcaParameter);
        }
    }
}
